name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4

      with:
        username: smart-118
        server: 104.41.201.128
        local_path: '.'
        remote_path: './sites/diyApi/'
        sftp_only: true
        password: f5T6uFbjPD$5kD9
        
      
  
