name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4

      # with:
      #   username: taskmoby
      #   server: 13.82.81.185
      #   local_path: '.'
      #   remote_path: './sites/smartapi'
      #   sftp_only: true
      #   password: InfomobySmartData2023!!

      # with:
      #   username: smart-118
      #   server: 104.41.201.128
      #   local_path: '.'
      #   remote_path: './sites/diyApi/'
      #   sftp_only: true
      #   password: f5T6uFbjPD$5kD9

      with:
        username: smart-118
        server: 104.41.201.128
        local_path: '.'
        remote_path: './sites/diyApi3/'
        sftp_only: true
        password: f5T6uFbjPD$5kD9
        

      # with:
      #   username: smartdata-sandbox-user
      #   server: 13.79.85.214
      #   local_path: '.'
      #   remote_path: './sites/smartDataApi/'
      #   sftp_only: true
      #   password: InfomobySmartData2023!!
      
  
